default branch가 hs라서...걍 다 삭제했어요..
hyeonsook95/kombucha pull request #1
Opened 2023-05-03 05:47 UTC by hyeonsook95

2023-05-07 07:31 UTC, kimevanjunseok requested changes
고생하셨습니다~~

2023-05-07 07:31 UTC, kimevanjunseok commented on src/main/java/com/kombucha/domain/posts/Posts.java
> +@NoArgsConstructor
기본 생성자를 public으로 생성할 때와 public으로 생성 안 할 때는 어떤 차이가 있을까요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/main/java/com/kombucha/service/posts/PostsService.java
> +    @Transactional
save에만 넣은 이유가 있나요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/main/java/com/kombucha/web/PostsApiController.java
> +        return postsService.save(postsSaveRequestDto);
상태코드도 전달해야하지 않을까요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/main/java/com/kombucha/web/dto/PostsUpdateRequestDto.java
> +    private Long id;
path로 받고 있는데 dto로 또 받는 이유가 있을까요? 만약 있다면 valid 체크도 필요하지 않을까요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/test/java/com/kombucha/kombucha/domain/posts/PostsRepositoryTest.java
> +@SpringBootTest
테스트시 해당 어노테이션을 쓰면 어떤 단점이 있을까요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/main/java/com/kombucha/domain/BaseTimeEntity.java
> +public class BaseTimeEntity {
created와 updated가 정상적으로 저장되는지 확인해보셨나요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/test/java/com/kombucha/kombucha/web/PostsApiControllerTest.java
> +public class PostsApiControllerTest {
테스트가 정상적으로 실행되는지 확인해보셨나요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/main/java/com/kombucha/web/dto/PostsResponseDto.java
> +@NoArgsConstructor
response에는 기본생성자가 필요없습니다. 왜일까요?

2023-05-07 07:31 UTC, kimevanjunseok commented on src/test/java/com/kombucha/kombucha/web/PostsApiControllerTest.java
> +        String url = "http://localhost:" + port + "/api/v1/posts";
테스트를 dev서버에서도 돌린다고하면 어떨까요?

2023-05-08 13:57 UTC, kimevanjunseok requested changes
추가 피드백 남깁니다.

2023-05-08 13:57 UTC, kimevanjunseok commented on src/main/java/com/kombucha/service/posts/PostsService.java
> +        Posts entity = postsRepository.findById(id).orElseThrow(()->new IllegalArgumentException("존재하지 않는 게시글입니다."));
다른 방식으로 삭제하는 방법이 있지 않을까요?

2023-05-08 13:57 UTC, kimevanjunseok commented on src/main/java/com/kombucha/domain/posts/Posts.java
> +        this.delete();
이렇게 재귀돌면 StackOverflowError 나지않을까요?

2023-05-18 13:27 UTC, hyeonsook95 commented on src/main/java/com/kombucha/domain/posts/Posts.java
> +@NoArgsConstructor
#2 
public 으로 생성자를 사용하면, 외부에서 누구든 생성자를 호출하여 객체를 생성할 수 있습니다. 이 방법의 단점은 누구든 생성자를 호출할 수 있기 때문에 불필요한 객체가 생성될 수 있다는 점입니다.

private 생성자를 사용할 수도 있는데, 이 때의 장점은 외부에서 메소드 호출이 불가능하기 때문에 내부에서만 객체를 생성할 수 있어 객체의 생성을 관리할 수 있다는 점입니다. private 생성자로 사용하는 방법에는 대표적으로 싱글톤 패턴 방법과 빌더 패턴 방법이 있습니다.

스프링에서는 싱글톤 컨테이너를 사용하여 객체 인스턴스를 싱글톤으로 관리합니다. 스프링 컨테이너에서 빈에 등록하여 싱글톤으로 관리하기 위해 생성자는 protected, public 의 접근 제한자를 가져야 합니다.

스프링 관점에서 빈에 등록될 객체의 생성자는 public과 protected로 선언할 수 있는데, 두 접근 제한자의 차이는 protected의 경우 개발을 진행할 때 직접 생성할 수 없고, public의 경우 직접 생성할 수 있다는 점입니다.

2023-05-18 13:31 UTC, hyeonsook95 commented on src/main/java/com/kombucha/service/posts/PostsService.java
> +    @Transactional
#3 
까먹었어요!

2023-05-20 08:11 UTC, hyeonsook95 commented on src/main/java/com/kombucha/web/PostsApiController.java
> +        return postsService.save(postsSaveRequestDto);
#4 
ResponseEntity로 반환하도록 수정하였습니다.

2023-05-20 08:24 UTC, hyeonsook95 commented on src/main/java/com/kombucha/web/dto/PostsUpdateRequestDto.java
> +    private Long id;
#5 
dto에 있을 필요가 없을것 같아요!

2023-05-21 10:20 UTC, hyeonsook95 commented on src/main/java/com/kombucha/service/posts/PostsService.java
> +        Posts entity = postsRepository.findById(id).orElseThrow(()->new IllegalArgumentException("존재하지 않는 게시글입니다."));
@kimevanjunseok 님 다른 방식의 삭제를 권하는 이유가 있을까요?

2023-05-21 10:51 UTC, hyeonsook95 commented on src/test/java/com/kombucha/kombucha/domain/posts/PostsRepositoryTest.java
> +@SpringBootTest
SpringbootTest 어노테이션을 쓰면, 테스트 시 모든 bean을 띄워놓고 테스트를 진행하기 때문에 비효율적입니다.

2023-05-21 12:03 UTC, kimevanjunseok commented on src/main/java/com/kombucha/service/posts/PostsService.java
> +        Posts entity = postsRepository.findById(id).orElseThrow(()->new IllegalArgumentException("존재하지 않는 게시글입니다."));
JPA 메서드로 제공하는 것 중에 delete라고 있습니다. 현재 로직으로 테스트 해보셨나요? 삭제 안되지 않나요?

2023-05-21 12:31 UTC, hyeonsook95 commented on src/main/java/com/kombucha/web/dto/PostsResponseDto.java
> +@NoArgsConstructor
### requestDto에서는 기본생성자가 필요한 이유
json 형식으로 요청을 받을 때, 자바에서 요청 값을 객체 형태로 변환해서 사용해야 한다.
그 변환하는 과정에서 viewer가 기본 생성자를 생성한 후 값을 주입하는 방식으로 변환하기 때문에 requestDto는 기본생성자가 필요하다.

2023-05-21 12:43 UTC, kimevanjunseok requested changes
추가 피드백 드려요

2023-05-21 12:43 UTC, kimevanjunseok commented on src/main/java/com/kombucha/web/PostsApiController.java
> +        postsService.save(postsSaveRequestDto);
생성이 되었을 때 아무 정보도 응답으로 안보내도 된다고 생각하시나요?

2023-05-21 12:43 UTC, kimevanjunseok commented on src/main/java/com/kombucha/web/PostsApiController.java
> +        postsService.update(id, postsUpdateRequestDto);
save 메서드와 똑같은 질문 드립니다.

2023-05-21 12:43 UTC, kimevanjunseok commented on src/main/java/com/kombucha/service/posts/PostsService.java
> +    @Transactional
해당 어노테이션은 class 위에 달면 모든 메서드에 적용됩니다.

2023-05-21 12:43 UTC, kimevanjunseok commented on src/main/java/com/kombucha/common/exceptions/CommonException.java
> +    private final StatusCode statusCode;
Exception에도 상태코드가 필요한가요?

2023-05-21 13:25 UTC, kimevanjunseok requested changes

2023-05-21 13:25 UTC, kimevanjunseok commented on src/main/java/com/kombucha/domain/BaseTimeEntity.java
> +public class BaseTimeEntity {
이건 common 패키지에 있어야하지 않을까요?

2023-06-01 16:15 UTC, hyeonsook95 commented on src/main/java/com/kombucha/common/exceptions/CommonException.java
> +    private final StatusCode statusCode;
Exception에 따라 상태코드를 다르게 반환해야하는 상황이 있지않을까요? 그래서 있어야 할 것 같은데요.

어떤 질문인지 구체적으로 예시들어주세요.

2023-06-03 12:54 UTC, merged